### ISSUE TITLE
Enable Vite support via https://github.com/brandcom/cakephp-vite

### ISSUE THREAD

**Issue by mbojanks** [ishanvyas22/cakephp-inertiajs#26]
Would you please consider integrating your cakephp-inertiajs (server-side) plugin with more recent Vite (than Laravel mix) client support, probably via https://github.com/brandcom/cakephp-vite ? Thanks in advance (for your response - at least)

**Comment by ishanvyas22** [comment]
👋🏼 Hey @mbojanks, this plugin internally uses [ishanvyas22/asset-mix](https://github.com/ishanvyas22/asset-mix) which uses Laravel mix - webpack as a bundler. Basically vite is modern replacement of webpack, etc. so what you are proposing is change from the core. To me, it looks like different package/plugin.

**Comment by ishanvyas22** [comment]
I want to mention here, it is possible to use vite (via https://github.com/brandcom/cakephp-vite) along with this plugin. Basically there is two side of things 1) front-end 2) back-end, this plugin tries to provide both to ease of development. So you can use back-end side of things of this package and ignore front-end of this plugin instead use your own custom configuration.

If you want you can try it out this way, feel free to try it yourself. In case you hit any roadblock I can try my best to help you.

**Comment by mbojanks** [comment]
Fair enough, thank you. I understand. Hopefully, I 'll manage to accomplish the solution on that path you suggested.
I really appreciate the help you offer. I will ask you for help in extreme need only, I promise.
