### ISSUE TITLE
Hi Add Example in folder or new repot Demo base

### ISSUE THREAD

**Issue by EOM** [ishanvyas22/cakephp-inertiajs#5]
Hi ,
Add Example in folder or new repot Demo base.
Example 3: Pages
- Hello InertiaJs in CakePHP
- Controller => var, array, objs, etc..
- View => Get Fecht data  json servelocal or ServerRemote

**Comment by ishanvyas22** [comment]
Hi @EOM, I'm already working on the demo project with CakePHP + Inertia.js. Soon I will release it.

In meanwhile play around with this plugin it's super easy to install and start with. Refer to the [inertiajs official website](https://inertiajs.com/) along with this plugin so you will have exact idea on how things are working. If you stuck anywhere just let me know here will try to help out as soon as possible.

**Comment by EOM** [comment]
Hi, follow the steps of REAME, but I have this error and cannot solve it.

![image](https://user-images.githubusercontent.com/1219132/93904259-0c6ba600-fcd0-11ea-85b4-f5e67327bdb4.png)

And I followed all the steps in a new CakePHP 3.9 project, I can't detect where the problem may be.

**Comment by ishanvyas22** [comment]
Hi @EOM, this has been fixed. I released a [new version](https://github.com/ishanvyas22/cakephp-inertiajs/releases/tag/1.1.1), please update package to version 1.1.1.

Let me know if it works. Cheers!

**Comment by EOM** [comment]
Hi, continue problem, change error:

Print error:
![image](https://user-images.githubusercontent.com/1219132/94086248-c8b49180-fde0-11ea-92c4-a4624b9f67cb.png)

code html out:
![image](https://user-images.githubusercontent.com/1219132/94086288-e7b32380-fde0-11ea-9be0-06cfa96850f6.png)

**Comment by ishanvyas22** [comment]
Yes, that's because you have to create a new Vue component into your `assets/js/Pages/Users/Index.vue` path.

**Comment by ishanvyas22** [comment]
All your components should go into the `assets/js/Pages/` path. Consider it your template root folder that will host all your views.

You can change it whatever you want by changing `webpack.mix.js` file. Just remember it should be in your `assets/js` folder.

For more info visit https://inertiajs.com/client-side-setup

**Comment by EOM** [comment]
OK, add component heloword.. continue errors

Print out:
![image](https://user-images.githubusercontent.com/1219132/94173611-8f286880-fe6a-11ea-85c0-1eef10f63917.png)

My tree change ok:
![image](https://user-images.githubusercontent.com/1219132/94173732-bb43e980-fe6a-11ea-8052-2b7ebdcabcc0.png)

**Comment by ishanvyas22** [comment]
Have you compiled your assets files? If not please run `npm run dev` to compile your js files. If you want to watch for every changes you make into your js files let `npm run watch` command in background.

Check out this link to understand more: https://laravel-mix.com/docs/5.0/workflow

This plugin uses Laravel mix under the hood using [AssetMix plugin](https://github.com/ishanvyas22/asset-mix) to quickly compile your assets.

**Comment by ishanvyas22** [comment]
@EOM I've created example project to demonstrate this plugin. Please have a look,
https://github.com/ishanvyas22/cakephp-pingcrm
