### ISSUE TITLE
Cannot find module for page

### ISSUE THREAD

**Issue by FinlayDaG33k** [ishanvyas22/cakephp-inertiajs#6]
Hii there,

I'm trying to use this plugin in my app but I've been stuck on a very specific issue the entire evening: `Error: Cannot find module './Pages/Display'`, similar to #5.
![](https://i.imgur.com/XsgIJBJ.png)

I've made the page using the scaffolding for `inertia-vue`.  
This is what my directory structure for the `assets` look like at this moment:
![](https://i.imgur.com/FGm9U8S.png)

I have compiled the assets using `yarn run watch` which is running in the background (making a change - say changing the title of the page - to the `app.js` in the `assets` directory gets reflected on the page just fine).

Any pointers to how to fix it?

**Comment by FinlayDaG33k** [comment]
I solved it by myself though it was just a random guess.
I had to create a file `@Pages/Pages/Display.vue` instead of `Pages/Display/Index.vue`.

**Comment by ishanvyas22** [comment]
Hey @FinlayDaG33k, thanks for opening up an issue. Glad you found out the solution of the problem. To give more clarity into this I've refurnished documentation and added note to highlight this problem. 

See #7 

Hope this helps!

**Comment by FinlayDaG33k** [comment]
Thanks, I'll have a look at it later tonight :)
